steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/planning-poker-cms:$TAG_NAME', '.']
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/[PROJECT_ID]/planning-poker-cms:$TAG_NAME"]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=./deployment/deployment.yaml
    - --image=gcr.io/$PROJECT_ID/planning-poker-cms:$TAG_NAME
    - --location=europe-west3-a	
    - --cluster=ds-tools