apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker-cms
  namespace: planning-poker
  labels:
    app: planning-poker-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-poker-cms
  template:
    metadata:
      labels:
        app: planning-poker-cms
    spec:
      containers:
        - name: planning-poker-cms
          image: gcr.io/ds-general/planning-poker-cms:0
          ports:
          - containerPort: 1337
          volumeMounts:
          - mountPath: /app/public/uploads
            name: media-uploads
      volumes:
      - name: media-uploads
        persistentVolumeClaim:
          claimName: media-pvc