kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc
  namespace: planning-poker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
